[pytest]

# =========================================================
# Test Discovery
# =========================================================

testpaths = tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*


# =========================================================
# Console Output
# =========================================================

addopts =
    -v
    -s
    --html=reports/reports.html
    --self-contained-html
    --reruns 2
    --reruns-delay 2
    --tb=short


# =========================================================
# Markers
# =========================================================

markers =
    smoke: Smoke tests
    sanity: Sanity tests
    regression: Regression tests
    flaky: Flaky tests
    slow: Slow tests


# =========================================================
# Timeout
# =========================================================

timeout = 60


# =========================================================
# Logging
# =========================================================

log_cli = false

log_cli_level = INFO

log_file = logs/pytest.log

log_file_level = INFO


# =========================================================
# Warnings
# =========================================================

filterwarnings =
    ignore::DeprecationWarning


# =========================================================
# Cache
# =========================================================

cache_dir = .pytest_cache